In [4]:
!pip install dill
!pip install requests

In [64]:
import pandas as pd
import dill
import requests
from io import StringIO
import requests
from io import StringIO
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import cross_val_score as cv
from sklearn.model_selection import StratifiedKFold
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.preprocessing import FunctionTransformer
from sklearn.impute import SimpleImputer
import sklearn
import dill

In [65]:
# GitHub raw content URL
github_url = 'https://raw.githubusercontent.com/Martinerramuspe/02-DATA_SCIENCIE/main/01-TELECOM_CHURN_PROJECT/05-DESPLIEGUE/Model_prepro.pkl'

In [66]:
response = requests.get(github_url)
Model_prepro = dill.loads(response.content)

In [67]:
#Prueba
file_id = "16ypxCIBr9wSGVEaXqWdZUfz9w4xzccwo"
download_link = f"https://drive.google.com/uc?id={file_id}"
response = requests.get(download_link)
csv_data = StringIO(response.text)
df = pd.read_csv(csv_data, encoding='utf-8')
# Predecimos con el pipeline
Model_prepro.predict(df)

array([0, 0, 0, ..., 0, 0, 0])

In [91]:
# Extraemos una fila, para ver si funciona el modelo
fila_extraida = df.iloc[[55]]
df1 = pd.DataFrame(fila_extraida)
Model_prepro.predict(df1)

array([1])

In [ ]:
# hacemos prueba creando una fila


In [94]:
# hacemos prueba creando una fila
New_data = {
    'State': 'NY',
    'Account length': 150,
    'Area code': 212,
    'International plan': 'Yes',
    'Voice mail plan': 'No',
    'Number vmail messages': 0,
    'Total day minutes': 300.5,
    'Total day calls': 120,
    'Total day charge': 50.75,
    'Total eve minutes': 250.3,
    'Total eve calls': 80,
    'Total eve charge': 21.15,
    'Total night minutes': 200.2,
    'Total night calls': 100,
    'Total night charge': 9.01,
    'Total intl minutes': 15.5,
    'Total intl calls': 4,
    'Total intl charge': 4.2,
    'Customer service calls': 2,
    'Churn': False
}

In [89]:
X = pd.DataFrame([New_data])

In [90]:
Model_prepro.predict(X)

array([1])

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2666 entries, 0 to 2665
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   State                   2666 non-null   object 
 1   Account length          2666 non-null   int64  
 2   Area code               2666 non-null   int64  
 3   International plan      2666 non-null   object 
 4   Voice mail plan         2666 non-null   object 
 5   Number vmail messages   2666 non-null   int64  
 6   Total day minutes       2666 non-null   float64
 7   Total day calls         2666 non-null   int64  
 8   Total day charge        2666 non-null   float64
 9   Total eve minutes       2666 non-null   float64
 10  Total eve calls         2666 non-null   int64  
 11  Total eve charge        2666 non-null   float64
 12  Total night minutes     2666 non-null   float64
 13  Total night calls       2666 non-null   int64  
 14  Total night charge      2666 non-null   

In [ ]:
df